import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_KR } from "next/font/google";
import "@/styles/globals.css";

/**
 * 영문 산세리프 폰트 (Geist)
 * - 모던하고 깔끔한 디자인의 영문 폰트
 * - 라틴 문자 최적화
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

/**
 * 모노스페이스 폰트 (Geist Mono)
 * - 코드 블록 및 기술 텍스트용
 * - 고정폭 폰트
 */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

/**
 * 한글 폰트 (Noto Sans Korean)
 * - Google이 개발한 한글 전용 산세리프 폰트
 * - 한글 가독성 최적화
 * - 여러 굵기(weight) 지원
 */
const notoSansKR = Noto_Sans_KR({
  variable: "--font-noto-sans-kr",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * 루트 레이아웃 컴포넌트
 * 
 * 전역 폰트 설정을 관리합니다.
 * - 한글: Noto Sans Korean (우선 순위)
 * - 영문: Geist Sans (폴백)
 * - 코드: Geist Mono
 * 
 * CSS 변수로 정의되어 전역에서 사용 가능합니다.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${notoSansKR.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
